### ISSUE TITLE
Website - home page

### ISSUE THREAD

**Issue by Sunitashelar** [project-sunbird/sunbird-commons#3]
1) Fix the header on the home page. It should always be visible even when the user scrolls the page.
2) Remove the social media icons in the footer for now as there are no pages to corroborate them.
3) Remove the testimonial from the footer for now.
4) Maintain the same font for 'Search' as the rest of the header text
5) Search does not work.

**Comment by lakhanmandloi** [comment]
1) WIP
2) Social mediaicons removed
3) testimonial removed
4) Done
5) Once all content is in place search data will be indexed

**Comment by lakhanmandloi** [comment]
1) Sticky Header Done

**Comment by kochhar** [comment]
@Sunitashelar could you please verify the fixes and close this issue?

**Comment by parthlawate** [comment]
Search is still pending. @lakhanmandloi I suggest we comment it out for now and come back to this once the NTP site urgency is out of the way. @kochhar Does that make sense ? Since we have used the base code in a little different way than they intended the indexer is not working as expected out of the box.

**Comment by kochhar** [comment]
thanks @parthlawate, seems reasonable in the interim. please do add an issue to track the re-addition of search.
