### ISSUE TITLE
Tracking sunbird docs build automation

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-commons#73]
@lakhanmandloi Please keep this updated with the current status of the docs build automation. Aiming

**Comment by lakhanmandloi** [comment]
@kochhar Hi, As we know the site will entirely be revamped with the new designs. I would suggest to go with this jekyll theme in new designs - https://github.com/CloudCannon/base-jekyll-template demo site - https://orange-ape.cloudvent.net/ .  

- This will remove the dependency of CircleCI as this theme do not have dependencies on any custom plugin or any js libs.
- We will get ready made search plugin which is right now dependent on react indexer in branch. 
-  with some development we will get the dynamic sidebar and other features which are already required in upcoming phases. Which are complex in branch.
- this theme is much cleaner and light weighted as compared to Branch

So i would suggest to invest time in new theme. . Until new theme is ready, we have already reduced the obstacle from the current one. 

The only problem which i see is the page contents is right now divided into ingredients. Ingredients were used to reuse the content in multiple pages. But since it is dependent on custom plugin it will go if we go with new theme. Migration will not be an issue but there will be no way to reuse the content blocks.

Let me know your thoughts

cc:
@Sunitashelar @parthlawate @coolbung

**Comment by kochhar** [comment]
Why can't the ingredients plugin be added to this theme?

**Comment by lakhanmandloi** [comment]
@kochhar it can be added , but i would like to avoid custom plugins as much as possible. So that we can build the site on github itself. And i do not think we reuse content very frequently. We use it at some places which can be maintained. 

@Sunitashelar @nawabahmadreshi can you pls confirm how frequently we reuse the same content on multiple pages ? So that we can take a call on above point

**Comment by nawabahmadreshi** [comment]
**Our concept of pages and ingredients is purely based on Content Engineering and we have modeled our content in this structure. Our focus is on scalability & re-usability of content.**
- This content modelling is envisioned with a futuristic approach expecting huge amounts of content and thus re-usability will be so handy and frequent.
- Currently, yes re-usability is less but it will grow proportionally as content will start growing.
cc:
@Sunitashelar

**Comment by Sunitashelar** [comment]
@kochhar @lakhanmandloi @nawabahmadreshi 
We have reused content quite heavily to create multiple artifacts. Content is also reused across pages of the site. This reuse will continue to increase. Hence, the need for ingredients and master pages will increase.

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi @Sunitashelar  Hi, Ok noted. We will not remove it.

**Comment by lakhanmandloi** [comment]
@kochhar  - 

Following were the points made in Fridays call  -

1. Installation and cache steps (NPM & gems) should be removed from the circleci steps . Installation of node modules should go in Docker images with global installation
2. Need to verify if files also gets deleted from s3 bucket if it is deleted from repo.
3. Build job should be removed from prod steps. Prod job should fetch site generated from S3  bucket which was generated in staging steps.
4. Same repo should be used to host code and generated site. gh-pages branch to host generated site. While master to hold the code of same site.

Is any point missing in this ?

cc: @parthlawate @coolbung

**Comment by lakhanmandloi** [comment]
Hi @kochhar ,

Here is the status of tasks -

- Installation and cache steps (NPM & gems) should be removed from the circleci steps . Installation of node modules should go in Docker images with global installation **- Done**
- Need to verify if files also gets deleted from s3 bucket if it is deleted from repo. - **Verified, it deletes**
- Build job should be removed from prod steps. Prod job should fetch site generated from S3 bucket which was generated in staging steps. **- Done**
- Same repo should be used to host code and generated site. gh-pages branch to host generated site. While master to hold the code of same site.  **- Done** While there is a minor issue for using common repo. It doesnt creates any problem but triggers a blank build.

Can we schedule a demo of this ?

cc: @parthlawate @coolbung

**Comment by kochhar** [comment]
Sounds good @lakhanmandloi can we schedule a demo tomorrow?
Thanks

**Comment by lakhanmandloi** [comment]
@kochhar Hi, Let me know you availability. I have ping you on Slack.

**Comment by lakhanmandloi** [comment]
@kochhar Closing this issue and creating new issues for CircleCI prod integration and Build promotions (Backlog).
