### ISSUE TITLE
Header Visibilty & Sidebar Nav.

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/sunbird-commons#85]
When we navigate through the pages , 
Either the header should be visible all the times on all the pages 
or the left navigation bar should be visible on all the pages to enable a user to navigate .

E.g 
http://www.sunbird.org/architecture/
This page has a sidenav but no header . 
http://www.sunbird.org/apis/bulkupload/
This page doesnt have a side nav but header get visible .
Is this intentional ? 
Cant we have a sidebar instead of header to maintain consistency. 

@lakhanmandloi 

cc:
@Sunitashelar

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi - Yes this is intentional. 

**For documentation pages -**

1. typically docs page content is long, user is expected to read the entire content. So having sidebar actually allows docs page to have more vertical space and less scroll. 
2. If you see the sidebar navigation has too many links when compared to horizontal navigation. Sidebar allows too many links to accommodate. While in horizontal it is doesn't.

for the other landing pages navigation items are less. And it is very common practice to have horizontal navigation at top.

**Comment by kochhar** [comment]
@nawabahmadreshi @lakhanmandloi is this issue resolved?

**Comment by nawabahmadreshi** [comment]
@kochhar this issue is addressed in new website design .
